### PR TITLE
AB#61880 Tabbed reports accessibility

### PR DESCRIPTION
**Pull request by phudson-he**
### Types of changes
-   [X] Bugfix (non-breaking change which fixes an issue)
-   [ ] New feature (non-breaking change which adds functionality)
-   [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### Description of Change

[AB#61880](https://dev.azure.com/hedev/Inventory/_workitems/edit/61880)

Ensure that the tabs in the Tabbed Report template are accessible so that:

- They are tab-able
- Icon colours are contrast compliant
- Their title is read and state is read out
- Making a tab active reads out that the active tab is now XYZ tab.

Peer Review: @RobOatesHistoricEngland 
Tester: @gouthamrandhi or Jamie McMinn
Merge Lead: @aj-he

### CODE REVIEW

**Review by RobOatesHistoricEngland — APPROVED** [review]
LGTM

**Comment by phudson-he** [comment]
@RobOatesHistoricEngland Just for info, I requested a re-review due to further changes made for screen readers when selecting different tabs

**Review by RobOatesHistoricEngland — APPROVED** [review]
LGTM

**Review by gouthamrandhi — APPROVED** [review]
Tested successfully by Jamie.

**Review by aj-he — APPROVED** [review]
LGTM

**Pull request merged**
