### PR TITLE
AB#62370 UI alignment and formatting

### PR DESCRIPTION
**Pull request by phudson-he**
Apply fixes for various alignment issues, including:
1. Notification icon position
2. New password validation message position
3. Password change success message position
4. Graph designer tree word wrapping
5. Left nav text alignment
6. In mobile view, ensure sub menu items display

### CODE REVIEW

**Review by csmith-he — COMMENTED** [review]
@phudson-he Can you confirm that the alignment of the side menu is correct?  I can't see a difference between the local version I've spun up and the screenshot showing an issue:

image

**Comment by phudson-he** [comment]
@csmith-he Yes all the below subitems (marked with the red lines) are now aligned, they were all over the place. Some of the icons appear to be smaller than others but thats just down to the particular icon used. The icons use a font and they are all the same font size, aligned to the left.
image

**Review by csmith-he — APPROVED** [review]
LGTM

**Review by gouthamrandhi — APPROVED** [review]
Tested successfully by Jamie.

**Comment by phudson-he** [comment]
Closing due to [new PR raised](https://github.com/HistoricEngland/arches/pull/292) including latest warden/main fixes

**Pull request closed without merging**
