### PR TITLE
Side navigation - add home link - AB#51442

### PR DESCRIPTION
**Pull request by khodgkinson-he**
RC BRANCH
--------------------------------
[AB#51442](https://hedev.visualstudio.com/76e71f30-b1ad-438a-a096-89ac98712f4e/_workitems/edit/51442) - KEY: (Side navigation) Add a link to the landing page

Add a new link as the first item in the side navigation with the text "Home" and a house icon, that navigates the user back to the landing page.

**Acceptance Criteria section.**

There is a link called "Home" as the first entry of the side navigation panel.
The link uses a "house icon"
The link navigates the user to "~/" (the default landing page)
The link must be keyboard accessible.
It must be accessible (check with WAVE and NVDA).

### CODE REVIEW

**Comment by khodgkinson-he** [comment]
@aj-he @Rehaan-Arif : Release candidate branchy  ^_^

**Review by phudson-he — APPROVED** [review]
Looks good

**Review by Rehaan-Arif — APPROVED** [review]
Testing completed

**Review by aj-he — APPROVED** [review]
looks good

**Pull request merged**
