### PR TITLE
8954 - Workflows Menu Reflow Add Scroll AB#42133 AB#45374 AB#45377 AB#45532

### PR DESCRIPTION
**Pull request by csmith-he**
- Vertical scroll bar added to content-panel class
- Also brings in other accessibility changes from keystone/acc

[AB#42133](https://hedev.visualstudio.com/76e71f30-b1ad-438a-a096-89ac98712f4e/_workitems/edit/42133)
[AB#45374](https://hedev.visualstudio.com/76e71f30-b1ad-438a-a096-89ac98712f4e/_workitems/edit/45374)
[AB#45377](https://hedev.visualstudio.com/76e71f30-b1ad-438a-a096-89ac98712f4e/_workitems/edit/45377)
[AB#45532](https://hedev.visualstudio.com/76e71f30-b1ad-438a-a096-89ac98712f4e/_workitems/edit/45532)

### CODE REVIEW

**Comment by aj-he** [comment]
@csmith-he can you also get @khodgkinson-he to review as you are pulling in his changes also.

Can this PR also get AB# tags for all tickets whose code is being brought in.

**Review by phudson-he — APPROVED** [review]
All looks fine to me

**Comment by csmith-he** [comment]
@aj-he , @khodgkinson-he added as a reviewer and the AB# tags added from my ticket and the ones in the commit history

**Review by aj-he — APPROVED** [review]
Mostly looks good although Paul needs to revisit AB#42133 before ACC release PR

**Review by khodgkinson-he — APPROVED** [review]
Yup, looks good! ^_^

**Pull request merged**
