### PR TITLE
Merge dev/6.1.x changes into keystone/dev

### PR DESCRIPTION
**Pull request by csmith-he**
Merge latest dev/6.1.x changes into keystone/dev

### CODE REVIEW

**Comment by aj-he** [comment]
@csmith-he @phudson-he I can see that there are issues with the header if I run branches `arches#keystone/dev_merge_dev_6_1_x` and `arches-her#keystone/dev` 

image

image

**Comment by aj-he** [comment]
image

**Review by aj-he — CHANGES_REQUESTED** [review]
Please resolve issues with the header/top right buttons which seem to have shifted into a column on the left.

**Comment by phudson-he** [comment]
@aj-he @csmith-he  I'm looking into this but so far haven't managed to get to the cause of this

**Comment by phudson-he** [comment]
This PR was superseded by #129, checked and all working so closing this.

**Pull request closed without merging**
