### PR TITLE
R112 merge in AB#53256 user cannot scroll entire page in landscape mode

### PR DESCRIPTION
**Pull request by phudson-he**
To include fix for scrolling in landscape orientation on mobile devices (max width 915px).

Please note...

Devices given landscape consideration as mentioned in the ticket were the iPhone 12 Pro, iPhone XR and Samsung Galaxy S20 Ultra. The Samsung model mentioned has the greatest screen width in landscape mode which is 915px, using the Chrome responsive dev tool.

This change was considered carefully and instead of having to create multiple landscape orientation css media queries, catering for multiple devices, I decided that it was much simpler to just increase the lowest 768px breakpoint media query to 915px.

### CODE REVIEW

**Review by RobOatesHistoricEngland — APPROVED** [review]
Looks good

**Review by RobOatesHistoricEngland — APPROVED** [review]
Looks fine

**Review by RobOatesHistoricEngland — APPROVED** [review]
Looks fine.

**Review by RobOatesHistoricEngland — APPROVED** [review]
Looks good

**Review by RobOatesHistoricEngland — APPROVED** [review]
Looks fine.

**Review by Rehaan-Arif — APPROVED** [review]
Tested Successfully

**Review by aj-he — APPROVED** [review]
looks good to me

**Pull request merged**
