### PR TITLE
CSS changes to wrap flexbox table contents AB#43904

### PR DESCRIPTION
**Pull request by RobOatesHistoricEngland**
[#AB43904](https://hedev.visualstudio.com/Inventory/_sprints/taskboard/Inventory/Inventory/Inventory/Sprint%2059?workitem=43904)

### CODE REVIEW

**Comment by aj-he** [comment]
@RobOatesHistoricEngland with my accessibility hat on, if I zoom in the row does not expand vertically to fit the content.

**Review by phudson-he — COMMENTED** [review]
Looks good to me

**Comment by aj-he** [comment]
@RobOatesHistoricEngland this seems to be restricting the wrap as disabling it allows text to start wrapping at high zooms. I'm editing the values in the card.
image

**Comment by RobOatesHistoricEngland** [comment]
@aj-he Could you elaborate on your issue, please. Maybe give me a call if easier ;)

**Comment by aj-he** [comment]
@RobOatesHistoricEngland In the editor, shrink the screen and the resource instance table content is hidden to the right.

image

**Review by phudson-he — COMMENTED** [review]
Fixed width removed, so row no longer cut off when editing card details

**Review by aj-he — APPROVED** [review]
looks good now

**Pull request merged**
