### PR TITLE
40386 acc bulk map manager

### PR DESCRIPTION
**Pull request by phudson-he**
To update keystone/acc with all bulk accessibility changes for the map manager

### CODE REVIEW

**Review by aj-he — CHANGES_REQUESTED** [review]
Can we get this horizontal scroll bar killed?

image

And it is a bit "Scrollbar City" when at a smaller viewport...

image

**Comment by aj-he** [comment]
And this appears if I use the skip to content link...
image

**Comment by phudson-he** [comment]
Scrollbar issues now fixed. Still working on the "skip to content" link which is actually a site-wide issue.

**Comment by phudson-he** [comment]
Will create a bug regarding the "skip to content" link issue as this is happening site wide. As far as I can see, together with the fixes for the scroll bars, this pr can be re-reviewed for approval etc. Bug 44686 created.

**Review by aj-he — APPROVED** [review]

**Comment by aj-he** [comment]
Looks fine to me

**Pull request merged**
