### PR TITLE
AB#55070 Articulate Guidance is opened based on User's group

### PR DESCRIPTION
**Pull request by csmith-he**
[AB#55070](https://hedev.visualstudio.com/76e71f30-b1ad-438a-a096-89ac98712f4e/_workitems/edit/55070)

The main help icon in the base manager has been altered so that the guidance available in Articulate is accessed rather than the inbuilt help.

If the user is only in the Guest group then they are sent to the basic guidance.  Everyone else is sent to the advanced guidance.

After discussion with @phudson-he I have set the a tag to open the link in a new tab, I have added an aria label and I have changed the icon to indicate the link takes the user to an external site (using the same icon as is used on the Corporate website for similar links).

Released keystone-config PR: https://hedev.visualstudio.com/Inventory/_git/keystone-config/pullrequest/4975

Dev Peer Reviewers: (for logic) @RobOatesHistoricEngland, (for front end) @phudson-he 
Tester: @Rehaan-Arif 
Merge lead: @aj-he

### CODE REVIEW

**Comment by RobOatesHistoricEngland** [comment]
@csmith-he Just a thought, instead of `user_is_guest` context and then introducing logic in to the template which duplicates the HTML as well, would it be cleaner to create a `help_url` context variable which pulls back one of the two URL's which could be stored as Library values and that way if the help URL's change over time - all we need to do is update the configuration, rather than perform a deploy?

**Review by phudson-he — APPROVED** [review]
Look good to me

**Comment by csmith-he** [comment]
> @csmith-he Just a thought, instead of `user_is_guest` context and then introducing logic in to the template which duplicates the HTML as well, would it be cleaner to create a `help_url` context variable which pulls back one of the two URL's which could be stored as Library values and that way if the help URL's change over time - all we need to do is update the configuration, rather than perform a deploy?

That sounds like a much neater solution, @RobOatesHistoricEngland.  I'll make the changes to the code and will re-request a review

**Comment by csmith-he** [comment]
@RobOatesHistoricEngland - Changes made as suggested.  Please be aware that there is a related pull request for the pipeline deployment side of things: https://hedev.visualstudio.com/Inventory/_git/keystone-config/pullrequest/4975

**Review by RobOatesHistoricEngland — APPROVED** [review]
Looks good

**Review by RobOatesHistoricEngland — APPROVED** [review]
Looks good.

**Review by Rehaan-Arif — APPROVED** [review]
Tested Successfully

**Review by aj-he — APPROVED** [review]
looks good

**Pull request merged**
