### PR TITLE
9010 Contrast Fix on Delete/Undo button focus in Workflows AB#45635

### PR DESCRIPTION
**Pull request by csmith-he**
[AB#45635](https://hedev.visualstudio.com/76e71f30-b1ad-438a-a096-89ac98712f4e/_workitems/edit/45635)

Changes the text colour to a value that contrasts with background colour to meet WCAG AAA requirements

### CODE REVIEW

**Comment by csmith-he** [comment]
@phudson-he - You've probably already peer reviewed this for me against Dev but for the sake of getting the process to stick in my mind, would you mind acting as my Dev peer review for this PR, please?

**Review by phudson-he — APPROVED** [review]
Looks good

**Comment by csmith-he** [comment]
@Rehaan-Arif - I believe you approved this before we started the new testing process.  This ticket has passed Dev peer review so I'm happy for it to go through candidate branch testing or for you to approve it as happy that it's already been tested.

**Review by Rehaan-Arif — APPROVED** [review]
Testing completed

**Review by aj-he — APPROVED** [review]
looks good

**Pull request merged**
