### PR TITLE
R111 merge in feature Add cookie management panel 50696 AB#50696

### PR DESCRIPTION
**Pull request by RobOatesHistoricEngland**
Add cookie management panel

[AB#50696](https://hedev.visualstudio.com/76e71f30-b1ad-438a-a096-89ac98712f4e/_workitems/edit/50696)

### CODE REVIEW

**Comment by RobOatesHistoricEngland** [comment]
@csmith-he Couldn't find Ray to add as a reviewer.

**Comment by csmith-he** [comment]
@RobOatesHistoricEngland - Hmm, I'm guessing he hasn't been added.  Bother, that's going to hold things up.  We might have to wait on this until @aj-he is back.  I'll at least do my peer review

**Review by csmith-he — APPROVED** [review]
Looks fine to me - running ok on a local environment

**Comment by csmith-he** [comment]
@RobOatesHistoricEngland You also need to add Andy as a reviewer in addition to assigning it to him, I think

**Review by csmith-he — APPROVED** [review]

**Review by Rehaan-Arif — APPROVED** [review]
Tested Successfully

**Review by aj-he — CHANGES_REQUESTED** [review]
branding needs to be at the project level so that it does not get overridden. Please remove branding and we'll review against the default styling.

**Review by csmith-he — APPROVED** [review]

**Review by Rehaan-Arif — APPROVED** [review]
Tested successfully

**Review by aj-he — APPROVED** [review]
looks good to me

**Pull request merged**
